use std::env;
use std::error::Error;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

fn main() {
    if let Err(error) = real_main() {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

fn real_main() -> Result<(), Box<dyn Error>> {
    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask should live under the workspace root")
        .to_path_buf();

    let mut args = env::args().skip(1);
    match args.next().as_deref() {
        Some("generate-bindings") => {
            let check = matches!(args.next().as_deref(), Some("--check"));
            generate_bindings(&repo_root, check)
        }
        Some("release") => release(&repo_root),
        Some("upgrade") => {
            let mut requested_libavif = None;
            let mut requested_libaom = None;

            while let Some(flag) = args.next() {
                match flag.as_str() {
                    "--libavif" => requested_libavif = args.next(),
                    "--libaom" => requested_libaom = args.next(),
                    other => return Err(format!("unexpected argument: {other}").into()),
                }
            }

            if requested_libavif.is_none() && requested_libaom.is_none() {
                return Err("upgrade requires at least one of --libavif or --libaom".into());
            }

            upgrade(&repo_root, requested_libavif, requested_libaom)
        }
        _ => Err(
            "usage:\n  cargo run -p xtask -- generate-bindings [--check]\n  cargo run -p xtask -- release\n  cargo run -p xtask -- upgrade [--libavif <version|latest>] [--libaom <version|latest>]".into(),
        ),
    }
}

fn release(repo_root: &Path) -> Result<(), Box<dyn Error>> {
    ensure_clean_workdir(repo_root)?;

    let version = read_package_version(&repo_root.join("Cargo.toml"))?;
    let tag = format!("v{version}");

    run(Command::new("git")
        .current_dir(repo_root)
        .arg("tag")
        .arg(&tag))?;
    let push_status = Command::new("git")
        .current_dir(repo_root)
        .arg("push")
        .arg("origin")
        .arg(&tag)
        .status()?;
    if !push_status.success() {
        return Err(format!(
            "failed to push {tag} to origin; the local tag was created successfully. Push it manually with: git push origin {tag}"
        )
        .into());
    }

    Ok(())
}

fn upgrade(
    repo_root: &Path,
    requested_libavif: Option<String>,
    requested_libaom: Option<String>,
) -> Result<(), Box<dyn Error>> {
    let mut versions = read_versions(&repo_root.join("upstream/versions.toml"))?;

    if let Some(requested) = requested_libavif {
        versions.libavif =
            resolve_version(&requested, "https://github.com/AOMediaCodec/libavif.git")?;
    }

    if let Some(requested) = requested_libaom {
        versions.libaom = resolve_version(&requested, "https://aomedia.googlesource.com/aom")?;
    }

    write_versions(&repo_root.join("upstream/versions.toml"), &versions)?;
    generate_bindings(repo_root, false)
}

fn generate_bindings(repo_root: &Path, check: bool) -> Result<(), Box<dyn Error>> {
    let wrapper = repo_root.join("include/wrapper.h");
    let versions = read_versions(&repo_root.join("upstream/versions.toml"))?;
    let source_dir = prepare_libavif_source(&versions.libavif)?;
    let include_dir = source_dir.join("include");
    let output = repo_root.join("src/bindings.rs");

    let generated = bindgen::Builder::default()
        .header(wrapper.display().to_string())
        .clang_arg(format!("-I{}", include_dir.display()))
        .allowlist_file(".*/avif\\.h")
        .derive_default(true)
        .generate_comments(true)
        .layout_tests(false)
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate()?
        .to_string();

    let generated =
        format!("// Regenerated by `cargo run -p xtask -- generate-bindings`.\n\n{generated}");
    let generated = rustfmt(&generated)?;

    if check {
        let current = fs::read_to_string(&output)?;
        if current != generated {
            return Err(
                "src/bindings.rs is out of date; run `cargo run -p xtask -- generate-bindings`"
                    .into(),
            );
        }
    } else {
        fs::write(output, generated)?;
    }

    Ok(())
}

fn prepare_libavif_source(version: &str) -> Result<PathBuf, Box<dyn Error>> {
    let root = env::temp_dir().join(format!(
        "jc-libavif-sys-bindgen-{}-{}",
        version.trim_start_matches('v'),
        std::process::id()
    ));
    let source_dir = root.join("libavif");
    download_and_unpack(
        &format!("https://github.com/AOMediaCodec/libavif/archive/refs/tags/{version}.tar.gz"),
        &format!("libavif-{}", version.trim_start_matches('v')),
        &source_dir,
        &root,
        "libavif",
    )?;
    Ok(source_dir)
}

fn resolve_version(requested: &str, remote: &str) -> Result<String, Box<dyn Error>> {
    if requested == "latest" {
        latest_tag(remote)
    } else {
        Ok(requested.to_owned())
    }
}

fn latest_tag(remote: &str) -> Result<String, Box<dyn Error>> {
    let output = command_output(
        Command::new("git")
            .arg("ls-remote")
            .arg("--tags")
            .arg(remote),
    )?;

    let mut best: Option<(Version, String)> = None;
    for line in output.lines() {
        let Some(reference) = line.split_whitespace().nth(1) else {
            continue;
        };
        if reference.ends_with("^{}") {
            continue;
        }
        let Some(tag) = reference.strip_prefix("refs/tags/") else {
            continue;
        };
        let Some(version) = Version::parse(tag) else {
            continue;
        };
        match &best {
            Some((current, _)) if &version <= current => {}
            _ => best = Some((version, tag.to_owned())),
        }
    }

    best.map(|(_, tag)| tag)
        .ok_or_else(|| format!("could not determine a stable tag from {remote}").into())
}

fn download_and_unpack(
    url: &str,
    extracted_dir_name: &str,
    destination: &Path,
    scratch_root: &Path,
    package: &str,
) -> Result<(), Box<dyn Error>> {
    let archive = scratch_root.join(format!("{package}.tar.gz"));
    let unpack_dir = scratch_root.join(format!("{package}-unpack"));

    if scratch_root.exists() {
        fs::remove_dir_all(scratch_root)?;
    }
    fs::create_dir_all(&unpack_dir)?;

    run(Command::new("curl")
        .arg("-fsSL")
        .arg("-o")
        .arg(&archive)
        .arg(url))?;

    run(Command::new("tar")
        .arg("-xzf")
        .arg(&archive)
        .arg("-C")
        .arg(&unpack_dir))?;

    let source = unpack_dir.join(extracted_dir_name);
    if let Some(parent) = destination.parent() {
        fs::create_dir_all(parent)?;
    }
    if destination.exists() {
        fs::remove_dir_all(destination)?;
    }
    fs::rename(&source, destination)?;
    fs::remove_file(archive)?;
    fs::remove_dir_all(unpack_dir)?;
    Ok(())
}

fn read_versions(path: &Path) -> Result<Versions, Box<dyn Error>> {
    let mut versions = Versions::default();
    for line in fs::read_to_string(path)?.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .ok_or_else(|| format!("invalid versions entry: {line}"))?;
        let value = value.trim().trim_matches('"').to_owned();
        match key.trim() {
            "libavif" => versions.libavif = value,
            "libaom" => versions.libaom = value,
            other => return Err(format!("unexpected versions key: {other}").into()),
        }
    }
    if versions.libavif.is_empty() || versions.libaom.is_empty() {
        return Err("upstream/versions.toml must set both libavif and libaom".into());
    }
    Ok(versions)
}

fn write_versions(path: &Path, versions: &Versions) -> Result<(), Box<dyn Error>> {
    fs::write(
        path,
        format!(
            "libavif = \"{}\"\nlibaom = \"{}\"\n",
            versions.libavif, versions.libaom
        ),
    )?;
    Ok(())
}

fn read_package_version(path: &Path) -> Result<String, Box<dyn Error>> {
    let mut in_package = false;

    for line in fs::read_to_string(path)?.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if line.starts_with('[') {
            in_package = line == "[package]";
            continue;
        }

        if !in_package {
            continue;
        }

        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        if key.trim() != "version" {
            continue;
        }

        let version = value.trim().trim_matches('"');
        if version.is_empty() {
            return Err(format!("package version is empty in {}", path.display()).into());
        }
        return Ok(version.to_owned());
    }

    Err(format!("could not find package.version in {}", path.display()).into())
}

fn ensure_clean_workdir(repo_root: &Path) -> Result<(), Box<dyn Error>> {
    let status = command_output(
        Command::new("git")
            .current_dir(repo_root)
            .arg("status")
            .arg("--short")
            .arg("--untracked-files=normal"),
    )?;

    if !status.trim().is_empty() {
        return Err("refusing to release from a dirty working tree".into());
    }

    Ok(())
}

fn run(command: &mut Command) -> Result<(), Box<dyn Error>> {
    let status = command.status()?;
    if !status.success() {
        return Err(format!("command {:?} failed with status {status}", command).into());
    }
    Ok(())
}

fn command_output(command: &mut Command) -> Result<String, Box<dyn Error>> {
    let output = command.output()?;
    if !output.status.success() {
        return Err(format!("command {:?} failed with status {}", command, output.status).into());
    }
    Ok(String::from_utf8(output.stdout)?)
}

fn rustfmt(source: &str) -> Result<String, Box<dyn Error>> {
    let mut child = Command::new("rustfmt")
        .arg("--emit")
        .arg("stdout")
        .arg("--edition")
        .arg("2024")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()?;

    child
        .stdin
        .as_mut()
        .ok_or("failed to open rustfmt stdin")?
        .write_all(source.as_bytes())?;

    let output = child.wait_with_output()?;
    if !output.status.success() {
        return Err("rustfmt failed while formatting generated bindings".into());
    }
    Ok(String::from_utf8(output.stdout)?)
}

#[derive(Default)]
struct Versions {
    libavif: String,
    libaom: String,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct Version {
    major: u64,
    minor: u64,
    patch: u64,
}

impl Version {
    fn parse(tag: &str) -> Option<Self> {
        let tag = tag.strip_prefix('v').unwrap_or(tag);
        let mut pieces = tag.split('.');
        let major = pieces.next()?.parse().ok()?;
        let minor = pieces.next()?.parse().ok()?;
        let patch = pieces.next()?.parse().ok()?;
        if pieces.next().is_some() {
            return None;
        }
        Some(Self {
            major,
            minor,
            patch,
        })
    }
}
